version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finsight-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://root:1234@cluster0.260lmcy.mongodb.net/
      - MONGO_DB=Finnalyze
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finsight-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
